import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Josh',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'admin1@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Karren',
      email: 'user@exmaple.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Small Rug Clean',
      slug: 'small-rug-clean',
      category: 'Rug',
      image: '/images/small2-rug.png',
      price: 35,
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
      description: 'A steamy rug clean.',
    },
    {
      name: 'Medium Rug Clean',
      slug: 'medium-rug-clean',
      category: 'Rug',
      image: '/images/medium3-rug.png',
      price: 45,
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
      description: 'A steamy rug clean.',
    },
    {
      name: 'Large Rug Clean',
      slug: 'rug-clean',
      category: 'Rug',
      image: '/images/large-rug.png',
      price: 50,
      rating: 4.5,
      numReviews: 8,
      countInStock: 4,
      description: 'A steamy rug clean.',
    },
    {
      name: 'Car Seat Clean',
      slug: 'car-seat-clean',
      category: 'Car',
      image: '/images/car-seat-clean.png',
      price: 45,
      rating: 4.6,
      numReviews: 9,
      countInStock: 4,
      description:
        'A car seat clean that will bring life back to your car seats.',
    },
    {
      name: 'Single Room',
      slug: 'single-room',
      category: 'room',
      image: '/images/choc-whirl-cake.png',
      price: 40,
      rating: 4.9,
      numReviews: 9,
      countInStock: 4,
      description:
        'Only need one room cleaned? This is the perfect clean for you!',
    },
    {
      name: 'Childrens Cake',
      slug: 'childrens-cake',
      category: 'Childrens',
      image: '/images/kids-pink-cake.png',
      price: 13,
      rating: 4.7,
      numReviews: 9,
      countInStock: 4,
      description: 'This cake is perfect for any childrens celebration',
    },
    {
      name: 'Christmas Cake',
      slug: 'chrsitmas-cake',
      category: 'Chirstmas',
      image: '/images/christmas-cake.png',
      price: 16,
      rating: 4.9,
      numReviews: 9,
      countInStock: 20,
      description:
        'Start your festive celebrations with this chunky christmas cake made to your liking',
    },
    {
      name: 'Celebration Cake',
      slug: 'celebration-cake',
      category: 'Celebration',
      image: '/images/happybirthday-cake.png',
      price: 15,
      rating: 4.6,
      numReviews: 9,
      countInStock: 20,
      description:
        'Share the Happy Birthday vibes with this cake for all, included custom message',
    },
  ],
};

export default data;
